package automat;
import javax.swing.*;

public class KoebGUI extends javax.swing.JPanel {

    Billetautomat ba;
    MainGUI ejer;
    JFrame koebGUI;
    UserGUI userGUI;
    
    public KoebGUI() {
        initComponents();
    }
    
    public void setup(Billetautomat ba, MainGUI ejer) {
        this.ba = ba;
        this.ejer = ejer;
        update();
    }
    
    public void update() {
        updateKurv();
        updatetxt();
    }
    public void updateKurv() {
        DefaultListModel listModel = new DefaultListModel();
        for( int i = 0; i < ba.kurv.size(); i++) {
            listModel.addElement(String.format("%d%s%s%s%d%s%.2f%s"
                    , ba.kurv.get(i).getAntalBilleter() 
                    , " stk    " 
                    , ba.kurv.get(i).getType() 
                    , "      " 
                    , ba.kurv.get(i).getZoner() 
                    , " zoner        "
                    , ba.kurv.get(i).getPris()
                    , " kr."));
        }
        kurvList.setModel(listModel);
    }
    public void updatetxt() {
        txtOutputTotal.setText(String.format("%.2f", ba.getTotalPris()));
        txtOutputIndsaet.setText(String.format("%.2f", ba.getBalance()));
        txtOutputMangler.setText(String.format("%.2f", ba.getTotalPris() - ba.getBalance()));
        txtOutputSaldo.setText(String.format("%.2f", ba.getBalance()));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        kurvList = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        btnIndsaet5 = new javax.swing.JButton();
        btnIndsaet10 = new javax.swing.JButton();
        btnIndsaet20 = new javax.swing.JButton();
        btnIndsaet1 = new javax.swing.JButton();
        btnIndsaet2 = new javax.swing.JButton();
        btnIndsaet50 = new javax.swing.JButton();
        btnIndsaet100 = new javax.swing.JButton();
        btnIndsaet200 = new javax.swing.JButton();
        btnIndsaet500 = new javax.swing.JButton();
        btnIndsaet1000 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtOutputSaldo = new javax.swing.JTextField();
        btnBetalKredit = new javax.swing.JButton();
        btnBetalKontant = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtOutputTotal = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtOutputIndsaet = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtOutputMangler = new javax.swing.JTextField();

        kurvList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(kurvList);

        jLabel1.setText("Indkøbskurv:");

        btnIndsaet5.setText("5,-");
        btnIndsaet5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIndsaet5ActionPerformed(evt);
            }
        });

        btnIndsaet10.setText("10,-");
        btnIndsaet10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIndsaet10ActionPerformed(evt);
            }
        });

        btnIndsaet20.setText("20,-");
        btnIndsaet20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIndsaet20ActionPerformed(evt);
            }
        });

        btnIndsaet1.setText("1,-");
        btnIndsaet1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIndsaet1ActionPerformed(evt);
            }
        });

        btnIndsaet2.setText("2,-");
        btnIndsaet2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIndsaet2ActionPerformed(evt);
            }
        });

        btnIndsaet50.setText("50,-");
        btnIndsaet50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIndsaet50ActionPerformed(evt);
            }
        });

        btnIndsaet100.setText("100,-");
        btnIndsaet100.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIndsaet100ActionPerformed(evt);
            }
        });

        btnIndsaet200.setText("200,-");
        btnIndsaet200.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIndsaet200ActionPerformed(evt);
            }
        });

        btnIndsaet500.setText("500,-");
        btnIndsaet500.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIndsaet500ActionPerformed(evt);
            }
        });

        btnIndsaet1000.setText("1000,-");
        btnIndsaet1000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIndsaet1000ActionPerformed(evt);
            }
        });

        jLabel2.setText("Balance:");

        txtOutputSaldo.setEditable(false);

        btnBetalKredit.setText("Kreditkort");
        btnBetalKredit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBetalKreditActionPerformed(evt);
            }
        });

        btnBetalKontant.setText("Kontant");
        btnBetalKontant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBetalKontantActionPerformed(evt);
            }
        });

        jLabel3.setText("Total:");

        txtOutputTotal.setEditable(false);
        txtOutputTotal.setText(" ");

        jLabel4.setText("Indsat:");

        txtOutputIndsaet.setEditable(false);
        txtOutputIndsaet.setText(" ");

        jLabel5.setText("Mangler:");

        txtOutputMangler.setEditable(false);
        txtOutputMangler.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtOutputTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtOutputIndsaet, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtOutputMangler, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtOutputSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnBetalKredit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBetalKontant, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btnIndsaet1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnIndsaet5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnIndsaet20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnIndsaet100, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnIndsaet500, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnIndsaet200, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnIndsaet50, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnIndsaet10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnIndsaet2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnIndsaet1000, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtOutputTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(txtOutputIndsaet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(txtOutputMangler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtOutputSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnIndsaet1)
                            .addComponent(btnIndsaet2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnIndsaet5)
                            .addComponent(btnIndsaet10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnIndsaet20)
                            .addComponent(btnIndsaet50))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnIndsaet100)
                            .addComponent(btnIndsaet200))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnIndsaet500)
                            .addComponent(btnIndsaet1000))
                        .addGap(7, 7, 7)
                        .addComponent(btnBetalKontant, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBetalKredit, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    private void btnIndsaet5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIndsaet5ActionPerformed
        ba.indsaetPenge(5);
        updatetxt();
        
    }//GEN-LAST:event_btnIndsaet5ActionPerformed
    private void btnBetalKreditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBetalKreditActionPerformed
        
        // Gør så man kan betale noget kontant og resten på kortet.
        if(ba.getBalance() < ba.getTotalPris()) {
            ba.indsaetPenge(ba.getTotalPris() - ba.getBalance());
        }

        if( ba.udskrivBilleter() > 0) {
            ba.returpenge();
            ejer.setTab(0);
            ejer.updateUserGUI();
        } else {
            System.err.println("FEJL i kredit betaling.");
        }
        
        update();
        
               
    }//GEN-LAST:event_btnBetalKreditActionPerformed
    private void btnIndsaet1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIndsaet1ActionPerformed
        ba.indsaetPenge(1);
        updatetxt();
    }//GEN-LAST:event_btnIndsaet1ActionPerformed
    private void btnIndsaet2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIndsaet2ActionPerformed
        ba.indsaetPenge(2);
        updatetxt();
    }//GEN-LAST:event_btnIndsaet2ActionPerformed
    private void btnIndsaet10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIndsaet10ActionPerformed
        ba.indsaetPenge(10);
        updatetxt();
    }//GEN-LAST:event_btnIndsaet10ActionPerformed
    private void btnIndsaet20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIndsaet20ActionPerformed
        ba.indsaetPenge(20);
        updatetxt();
    }//GEN-LAST:event_btnIndsaet20ActionPerformed
    private void btnIndsaet50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIndsaet50ActionPerformed
        ba.indsaetPenge(50);
        updatetxt();
    }//GEN-LAST:event_btnIndsaet50ActionPerformed
    private void btnIndsaet100ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIndsaet100ActionPerformed
        ba.indsaetPenge(100);
        updatetxt();
    }//GEN-LAST:event_btnIndsaet100ActionPerformed
    private void btnIndsaet200ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIndsaet200ActionPerformed
        ba.indsaetPenge(200);
        updatetxt();
    }//GEN-LAST:event_btnIndsaet200ActionPerformed
    private void btnIndsaet500ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIndsaet500ActionPerformed
        ba.indsaetPenge(500);
        updatetxt();
    }//GEN-LAST:event_btnIndsaet500ActionPerformed
    private void btnIndsaet1000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIndsaet1000ActionPerformed
        ba.indsaetPenge(1000);
        updatetxt();
    }//GEN-LAST:event_btnIndsaet1000ActionPerformed
    private void btnBetalKontantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBetalKontantActionPerformed
        if( ba.getBalance() >= ba.getTotalPris()) {
            if( ba.udskrivBilleter() > 0) {
                ba.returpenge();
                ejer.setTab(0);
                ejer.updateUserGUI();
            } else {
                System.err.println("FEJL i Kontant betaling.");
            }
        }
        update();
    }//GEN-LAST:event_btnBetalKontantActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBetalKontant;
    private javax.swing.JButton btnBetalKredit;
    private javax.swing.JButton btnIndsaet1;
    private javax.swing.JButton btnIndsaet10;
    private javax.swing.JButton btnIndsaet100;
    private javax.swing.JButton btnIndsaet1000;
    private javax.swing.JButton btnIndsaet2;
    private javax.swing.JButton btnIndsaet20;
    private javax.swing.JButton btnIndsaet200;
    private javax.swing.JButton btnIndsaet5;
    private javax.swing.JButton btnIndsaet50;
    private javax.swing.JButton btnIndsaet500;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> kurvList;
    private javax.swing.JTextField txtOutputIndsaet;
    private javax.swing.JTextField txtOutputMangler;
    private javax.swing.JTextField txtOutputSaldo;
    private javax.swing.JTextField txtOutputTotal;
    // End of variables declaration//GEN-END:variables
}
