/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package automat;

import javax.swing.*;

public class KoebGUI extends javax.swing.JPanel {

    Billetautomat ba;
    JFrame koebGUI;
    UserGUI userGUI;
    
    public KoebGUI() {
        initComponents();
    }
    public void update() {
        updateKurv();
        updatetxt();
    }
    public void updateKurv() {
        DefaultListModel listModel = new DefaultListModel();
        for( int i = 0; i < ba.kurv.size(); i++) {
            listModel.addElement(String.format("%d%s%s%s%d%s%.2f%s"
                    , ba.kurv.get(i).getAntalBilleter() 
                    , " stk    " 
                    , ba.kurv.get(i).getType() 
                    , "      " 
                    , ba.kurv.get(i).getZoner() 
                    , " zoner        "
                    , ba.kurv.get(i).getPris()
                    , " kr."));
        }
        kurvList.setModel(listModel);
    }
    public void updatetxt() {
        txtOutputTotal.setText(String.format("%.2f", ba.getTotalPris()));
        txtOutputIndsæt.setText(String.format("%.2f", ba.getBalance()));
        txtOutputMangler.setText(String.format("%.2f", ba.getTotalPris() - ba.getBalance()));
        txtOutputSaldo.setText(String.format("%.2f", ba.getBalance()));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        kurvList = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        btnIndsæt5 = new javax.swing.JButton();
        btnIndsæt10 = new javax.swing.JButton();
        btnIndsæt20 = new javax.swing.JButton();
        btnIndsæt1 = new javax.swing.JButton();
        btnIndsæt2 = new javax.swing.JButton();
        btnIndsæt50 = new javax.swing.JButton();
        btnIndsæt100 = new javax.swing.JButton();
        btnIndsæt200 = new javax.swing.JButton();
        btnIndsæt500 = new javax.swing.JButton();
        btnIndsæt1000 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtOutputSaldo = new javax.swing.JTextField();
        btnBetalKredit = new javax.swing.JButton();
        btnBetalKontant = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtOutputTotal = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtOutputIndsæt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtOutputMangler = new javax.swing.JTextField();

        kurvList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(kurvList);

        jLabel1.setText("Indkøbskurv:");

        btnIndsæt5.setText("5,-");
        btnIndsæt5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIndsæt5ActionPerformed(evt);
            }
        });

        btnIndsæt10.setText("10,-");
        btnIndsæt10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIndsæt10ActionPerformed(evt);
            }
        });

        btnIndsæt20.setText("20,-");
        btnIndsæt20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIndsæt20ActionPerformed(evt);
            }
        });

        btnIndsæt1.setText("1,-");
        btnIndsæt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIndsæt1ActionPerformed(evt);
            }
        });

        btnIndsæt2.setText("2,-");
        btnIndsæt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIndsæt2ActionPerformed(evt);
            }
        });

        btnIndsæt50.setText("50,-");
        btnIndsæt50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIndsæt50ActionPerformed(evt);
            }
        });

        btnIndsæt100.setText("100,-");
        btnIndsæt100.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIndsæt100ActionPerformed(evt);
            }
        });

        btnIndsæt200.setText("200,-");
        btnIndsæt200.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIndsæt200ActionPerformed(evt);
            }
        });

        btnIndsæt500.setText("500,-");
        btnIndsæt500.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIndsæt500ActionPerformed(evt);
            }
        });

        btnIndsæt1000.setText("1000,-");
        btnIndsæt1000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIndsæt1000ActionPerformed(evt);
            }
        });

        jLabel2.setText("Balance:");

        txtOutputSaldo.setEditable(false);

        btnBetalKredit.setText("Kreditkort");
        btnBetalKredit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBetalKreditActionPerformed(evt);
            }
        });

        btnBetalKontant.setText("Kontant");
        btnBetalKontant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBetalKontantActionPerformed(evt);
            }
        });

        jLabel3.setText("Total:");

        txtOutputTotal.setEditable(false);
        txtOutputTotal.setText(" ");

        jLabel4.setText("Indsat:");

        txtOutputIndsæt.setEditable(false);
        txtOutputIndsæt.setText(" ");

        jLabel5.setText("Mangler:");

        txtOutputMangler.setEditable(false);
        txtOutputMangler.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtOutputTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtOutputIndsæt, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtOutputMangler, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtOutputSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnBetalKredit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBetalKontant, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btnIndsæt1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnIndsæt5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnIndsæt20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnIndsæt100, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnIndsæt500, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnIndsæt200, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnIndsæt50, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnIndsæt10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnIndsæt2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnIndsæt1000, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtOutputTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(txtOutputIndsæt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(txtOutputMangler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtOutputSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnIndsæt1)
                            .addComponent(btnIndsæt2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnIndsæt5)
                            .addComponent(btnIndsæt10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnIndsæt20)
                            .addComponent(btnIndsæt50))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnIndsæt100)
                            .addComponent(btnIndsæt200))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnIndsæt500)
                            .addComponent(btnIndsæt1000))
                        .addGap(7, 7, 7)
                        .addComponent(btnBetalKontant, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBetalKredit, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    private void btnIndsæt5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIndsæt5ActionPerformed
        ba.indsaetPenge(5);
        updatetxt();
    }//GEN-LAST:event_btnIndsæt5ActionPerformed
    private void btnBetalKreditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBetalKreditActionPerformed
        
        // Gør så man kan betale noget kontant og resten på kortet.
        ba.indsaetPenge(ba.getTotalPris() - ba.getBalance());
        
        
        if( ba.udskrivBilleter() > 0) {
            userGUI.update();
            koebGUI.dispose();
        } else {
            System.err.println("FEJL i kredit betaling.");
        }
        
        update();
        
    }//GEN-LAST:event_btnBetalKreditActionPerformed
    private void btnIndsæt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIndsæt1ActionPerformed
        ba.indsaetPenge(1);
        updatetxt();
    }//GEN-LAST:event_btnIndsæt1ActionPerformed
    private void btnIndsæt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIndsæt2ActionPerformed
        ba.indsaetPenge(2);
        updatetxt();
    }//GEN-LAST:event_btnIndsæt2ActionPerformed
    private void btnIndsæt10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIndsæt10ActionPerformed
        ba.indsaetPenge(10);
        updatetxt();
    }//GEN-LAST:event_btnIndsæt10ActionPerformed
    private void btnIndsæt20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIndsæt20ActionPerformed
        ba.indsaetPenge(20);
        updatetxt();
    }//GEN-LAST:event_btnIndsæt20ActionPerformed
    private void btnIndsæt50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIndsæt50ActionPerformed
        ba.indsaetPenge(50);
        updatetxt();
    }//GEN-LAST:event_btnIndsæt50ActionPerformed
    private void btnIndsæt100ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIndsæt100ActionPerformed
        ba.indsaetPenge(100);
        updatetxt();
    }//GEN-LAST:event_btnIndsæt100ActionPerformed
    private void btnIndsæt200ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIndsæt200ActionPerformed
        ba.indsaetPenge(200);
        updatetxt();
    }//GEN-LAST:event_btnIndsæt200ActionPerformed
    private void btnIndsæt500ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIndsæt500ActionPerformed
        ba.indsaetPenge(500);
        updatetxt();
    }//GEN-LAST:event_btnIndsæt500ActionPerformed
    private void btnIndsæt1000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIndsæt1000ActionPerformed
        ba.indsaetPenge(1000);
        updatetxt();
    }//GEN-LAST:event_btnIndsæt1000ActionPerformed
    private void btnBetalKontantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBetalKontantActionPerformed
        if( ba.getBalance() >= ba.getTotalPris()) {
            if( ba.udskrivBilleter() > 0) {
                ba.returpenge();
                userGUI.update();
                koebGUI.dispose();
            } else {
                System.err.println("FEJL i Kontant betaling.");
            }
        }
        update();
    }//GEN-LAST:event_btnBetalKontantActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBetalKontant;
    private javax.swing.JButton btnBetalKredit;
    private javax.swing.JButton btnIndsæt1;
    private javax.swing.JButton btnIndsæt10;
    private javax.swing.JButton btnIndsæt100;
    private javax.swing.JButton btnIndsæt1000;
    private javax.swing.JButton btnIndsæt2;
    private javax.swing.JButton btnIndsæt20;
    private javax.swing.JButton btnIndsæt200;
    private javax.swing.JButton btnIndsæt5;
    private javax.swing.JButton btnIndsæt50;
    private javax.swing.JButton btnIndsæt500;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> kurvList;
    private javax.swing.JTextField txtOutputIndsæt;
    private javax.swing.JTextField txtOutputMangler;
    private javax.swing.JTextField txtOutputSaldo;
    private javax.swing.JTextField txtOutputTotal;
    // End of variables declaration//GEN-END:variables
}
